/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Models.Goal;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fahadxhussain
 */
public class AddGoalView extends javax.swing.JFrame {

    /**
     * Creates new form AddGoalVIew
     */
    public AddGoalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddGoalHeader = new javax.swing.JLabel();
        GoalLabel = new javax.swing.JLabel();
        goalInput = new javax.swing.JTextField();
        deadlineLabel = new javax.swing.JLabel();
        dateInput = new com.toedter.calendar.JDateChooser();
        doneButton = new javax.swing.JLabel();
        crossButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 600));
        setMinimumSize(new java.awt.Dimension(400, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setSize(new java.awt.Dimension(400, 600));

        AddGoalHeader.setBackground(new java.awt.Color(0, 102, 102));
        AddGoalHeader.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        AddGoalHeader.setForeground(new java.awt.Color(255, 255, 255));
        AddGoalHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddGoalHeader.setText("Add Goal");
        AddGoalHeader.setOpaque(true);
        AddGoalHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddGoalHeaderMouseClicked(evt);
            }
        });

        GoalLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        GoalLabel.setForeground(new java.awt.Color(0, 102, 102));
        GoalLabel.setText("Goal");

        goalInput.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        goalInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        deadlineLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        deadlineLabel.setForeground(new java.awt.Color(0, 102, 102));
        deadlineLabel.setText("DeadLine");

        doneButton.setBackground(new java.awt.Color(0, 102, 102));
        doneButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doneButton.setText("Done");
        doneButton.setOpaque(true);
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneButtonMouseClicked(evt);
            }
        });

        crossButton.setFont(new java.awt.Font("Kefa", 1, 14)); // NOI18N
        crossButton.setForeground(new java.awt.Color(0, 102, 102));
        crossButton.setText("x");
        crossButton.setBorder(null);
        crossButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(goalInput, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(GoalLabel)
                                    .addComponent(deadlineLabel)
                                    .addComponent(dateInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(AddGoalHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(crossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(AddGoalHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(crossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91)
                .addComponent(GoalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(deadlineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddGoalHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddGoalHeaderMouseClicked
       
    }//GEN-LAST:event_AddGoalHeaderMouseClicked

    private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseClicked
        String goalInput = this.goalInput.getText();
        String deadLine = null;
        Date date = this.dateInput.getDate();

        if (date != null) {
            deadLine = date.toString();
            String[] singobj = deadLine.split(" ");
            if (singobj.length >= 6) {
                deadLine = singobj[0] + " " + singobj[1] + " " + singobj[2] + " " + singobj[5];
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Invalid date format", "", JOptionPane.OK_OPTION);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Please select a deadline", "", JOptionPane.OK_OPTION);
            return;
        }

        // Validate required fields
        if (goalInput.isEmpty() || deadLine.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Please fill all the required fields", "", JOptionPane.OK_OPTION);
            return;
        }

        // Create and use the Goal object
        Goal goal = new Goal(goalInput, deadLine);

        // Display success message
        JOptionPane.showMessageDialog(new JFrame(), "Goal Added Successfully. Please refresh the page", "Done", JOptionPane.DEFAULT_OPTION);

        // Dispose the current window
        this.dispose();
        
        
        
    }//GEN-LAST:event_doneButtonMouseClicked

    private void crossButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_crossButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddGoalHeader;
    private javax.swing.JLabel GoalLabel;
    private javax.swing.JButton crossButton;
    private com.toedter.calendar.JDateChooser dateInput;
    private javax.swing.JLabel deadlineLabel;
    private javax.swing.JLabel doneButton;
    private javax.swing.JTextField goalInput;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
