/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Models.Grade;
import static java.lang.Integer.parseInt;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fahadxhussain
 */
public class AddGradesView extends javax.swing.JFrame {

    /**
     * Creates new form AddGradesView
     */
    public AddGradesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registeredCoursesHeading2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addGradesHeader = new javax.swing.JLabel();
        GPALabel = new javax.swing.JLabel();
        semesterInput = new javax.swing.JTextField();
        semesterLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        gradeInput = new javax.swing.JTextField();
        gpaInput = new javax.swing.JTextField();
        doneButton = new javax.swing.JLabel();
        crossButton = new javax.swing.JButton();

        registeredCoursesHeading2.setBackground(new java.awt.Color(0, 102, 102));
        registeredCoursesHeading2.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        registeredCoursesHeading2.setForeground(new java.awt.Color(255, 255, 255));
        registeredCoursesHeading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registeredCoursesHeading2.setText("Add Grades");
        registeredCoursesHeading2.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 600));
        setSize(new java.awt.Dimension(400, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setSize(new java.awt.Dimension(400, 600));

        addGradesHeader.setBackground(new java.awt.Color(0, 102, 102));
        addGradesHeader.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        addGradesHeader.setForeground(new java.awt.Color(255, 255, 255));
        addGradesHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addGradesHeader.setText("Add Grades");
        addGradesHeader.setOpaque(true);

        GPALabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        GPALabel.setForeground(new java.awt.Color(0, 102, 102));
        GPALabel.setText("GPA");

        semesterInput.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        semesterInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        semesterLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(0, 102, 102));
        semesterLabel.setText("Semester");

        gradeLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(0, 102, 102));
        gradeLabel.setText("Grade");

        gradeInput.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        gradeInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        gpaInput.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        gpaInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        doneButton.setBackground(new java.awt.Color(0, 102, 102));
        doneButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doneButton.setText("Done");
        doneButton.setOpaque(true);
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneButtonMouseClicked(evt);
            }
        });

        crossButton.setFont(new java.awt.Font("Kefa", 1, 14)); // NOI18N
        crossButton.setForeground(new java.awt.Color(0, 102, 102));
        crossButton.setText("x");
        crossButton.setBorder(null);
        crossButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semesterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GPALabel)
                                    .addComponent(gradeLabel)
                                    .addComponent(semesterLabel)
                                    .addComponent(gpaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gradeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(addGradesHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(crossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(crossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addGradesHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(semesterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semesterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GPALabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(gradeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void crossButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_crossButtonActionPerformed

    private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseClicked
        String semesterText = this.semesterInput.getText();
        String gpaText = this.gpaInput.getText();
        String grades = this.gradeInput.getText();

        // Validate and parse semester
        int semester;
        try {
            semester = Integer.parseInt(semesterText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid semester value. Please enter a valid integer.", "", JOptionPane.OK_OPTION);
            return;
        }

        // Validate and parse GPA
        double gpa;
        try {
            gpa = Double.parseDouble(gpaText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid GPA value. Please enter a valid decimal number.", "", JOptionPane.OK_OPTION);
            return;
        }

        // Validate other required fields
        if (semesterText.isEmpty() || gpaText.isEmpty() || grades.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Please fill all the required fields", "", JOptionPane.OK_OPTION);
            return;
        }

        // Create and use the Grade object
        Grade grade = new Grade(semester, gpa, grades);
        JOptionPane.showMessageDialog(new JFrame(), "Grades Added Successfully. Please refresh the page", "Done", JOptionPane.DEFAULT_OPTION);

        // Dispose the current window
        this.dispose();
        
        
    }//GEN-LAST:event_doneButtonMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GPALabel;
    private javax.swing.JLabel addGradesHeader;
    private javax.swing.JButton crossButton;
    private javax.swing.JLabel doneButton;
    private javax.swing.JTextField gpaInput;
    private javax.swing.JTextField gradeInput;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel registeredCoursesHeading2;
    private javax.swing.JTextField semesterInput;
    private javax.swing.JLabel semesterLabel;
    // End of variables declaration//GEN-END:variables
}
