/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Models.Course;
import static java.lang.Integer.parseInt;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fahadxhussain
 */
public class CourseRegView extends javax.swing.JFrame {
    
    /**
     * Creates new form CourseRegView
     */
    public CourseRegView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registeredCoursesHeading1 = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        courseName = new javax.swing.JTextField();
        creditHoursLabel = new javax.swing.JLabel();
        DiffLevelLabel = new javax.swing.JLabel();
        creditHours = new javax.swing.JTextField();
        doneButton = new javax.swing.JLabel();
        crossButton = new javax.swing.JButton();
        GPAlabel = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        difficultyLevel = new javax.swing.JComboBox<>();
        courseNameLabel1 = new javax.swing.JLabel();
        courseCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 800));
        setMinimumSize(new java.awt.Dimension(400, 800));
        setSize(new java.awt.Dimension(400, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBounds(new java.awt.Rectangle(0, 0, 400, 800));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 800));

        registeredCoursesHeading1.setBackground(new java.awt.Color(0, 102, 102));
        registeredCoursesHeading1.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        registeredCoursesHeading1.setForeground(new java.awt.Color(255, 255, 255));
        registeredCoursesHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registeredCoursesHeading1.setText("Register Course");
        registeredCoursesHeading1.setOpaque(true);

        courseNameLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        courseNameLabel.setForeground(new java.awt.Color(0, 102, 102));
        courseNameLabel.setText("Course Name");

        courseName.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        courseName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        creditHoursLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        creditHoursLabel.setForeground(new java.awt.Color(0, 102, 102));
        creditHoursLabel.setText("Credit Hours");

        DiffLevelLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        DiffLevelLabel.setForeground(new java.awt.Color(0, 102, 102));
        DiffLevelLabel.setText("Difficulty Level");

        creditHours.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        creditHours.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        doneButton.setBackground(new java.awt.Color(0, 102, 102));
        doneButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doneButton.setText("Done");
        doneButton.setOpaque(true);
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneButtonMouseClicked(evt);
            }
        });

        crossButton.setFont(new java.awt.Font("Kefa", 1, 14)); // NOI18N
        crossButton.setForeground(new java.awt.Color(0, 102, 102));
        crossButton.setText("x");
        crossButton.setBorder(null);
        crossButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossButtonActionPerformed(evt);
            }
        });

        GPAlabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        GPAlabel.setForeground(new java.awt.Color(0, 102, 102));
        GPAlabel.setText("GPA");

        gpa.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        gpa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        difficultyLevel.setFont(new java.awt.Font("Kefa", 1, 14)); // NOI18N
        difficultyLevel.setForeground(new java.awt.Color(0, 102, 102));
        difficultyLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));
        difficultyLevel.setMaximumSize(new java.awt.Dimension(72, 23));
        difficultyLevel.setMinimumSize(new java.awt.Dimension(72, 23));
        difficultyLevel.setPreferredSize(new java.awt.Dimension(72, 23));

        courseNameLabel1.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        courseNameLabel1.setForeground(new java.awt.Color(0, 102, 102));
        courseNameLabel1.setText("Course Code");

        courseCode.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        courseCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(registeredCoursesHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(crossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseNameLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(courseName, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(courseNameLabel)
                                .addComponent(creditHoursLabel)
                                .addComponent(creditHours, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(DiffLevelLabel)
                                .addComponent(GPAlabel)
                                .addComponent(gpa, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(difficultyLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(courseCode, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(registeredCoursesHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(crossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(courseNameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(courseNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creditHoursLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditHours, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GPAlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DiffLevelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseClicked
        String courseCode = this.courseCode.getText();
        String courseName = this.courseName.getText();
        Integer creditHours = null;
        Double gpa = null;
        String difficultyLevel = (String) this.difficultyLevel.getSelectedItem();

    // Validate and parse credit hours
        try {
            creditHours = Integer.parseInt(this.creditHours.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid credit hours", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate and parse GPA
        try {
            gpa = Double.parseDouble(this.gpa.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid GPA", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate required fields
        if (courseCode.equals("") || courseName.equals("") || difficultyLevel == null || difficultyLevel.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Please fill all the required fields", "", JOptionPane.OK_OPTION);
            return;
        }

        // Validate credit hours
        if (creditHours > 4 || creditHours < 1) {
            JOptionPane.showMessageDialog(new JFrame(), "Credit hours must be between 1 and 4", "", JOptionPane.OK_OPTION);
            return;
        }

        // Validate GPA
        if (gpa > 4.0 || gpa < 1.0) {
            JOptionPane.showMessageDialog(new JFrame(), "GPA must be between 1.0 and 4.0", "", JOptionPane.OK_OPTION);
            return;
        }

        // Create and use the Course object
        Course course = new Course(courseCode, courseName, creditHours, gpa, difficultyLevel);
        JOptionPane.showMessageDialog(new JFrame(), "Course Added Successfully", "", JOptionPane.OK_OPTION);
        this.dispose();
    
        
    }//GEN-LAST:event_doneButtonMouseClicked

    private void crossButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_crossButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiffLevelLabel;
    private javax.swing.JLabel GPAlabel;
    private javax.swing.JTextField courseCode;
    private javax.swing.JTextField courseName;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JLabel courseNameLabel1;
    private javax.swing.JTextField creditHours;
    private javax.swing.JLabel creditHoursLabel;
    private javax.swing.JButton crossButton;
    private javax.swing.JComboBox<String> difficultyLevel;
    private javax.swing.JLabel doneButton;
    private javax.swing.JTextField gpa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel registeredCoursesHeading1;
    // End of variables declaration//GEN-END:variables
}
