/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import Database.DatabaseConnection;
import Models.CurrentUser;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author fahadxhussain
 */
public class CoursesView extends javax.swing.JFrame {
    private Connection connection;

    /**
     * Creates new form Courses
     */
    public CoursesView() {
        initComponents();
        updateCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        registeredCoursesHeading = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        registerCourseButton = new javax.swing.JLabel();
        refreshButton = new javax.swing.JLabel();
        deleteCourseButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));

        coursesTable.setFont(new java.awt.Font("Al Nile", 1, 14)); // NOI18N
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseCode", "Course", "Credit Hours", "Difficulty", "GPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        coursesTable.setPreferredSize(new java.awt.Dimension(400, 400));
        coursesTable.setRowHeight(32);
        coursesTable.setShowGrid(true);
        jScrollPane1.setViewportView(coursesTable);
        if (coursesTable.getColumnModel().getColumnCount() > 0) {
            coursesTable.getColumnModel().getColumn(0).setMinWidth(125);
            coursesTable.getColumnModel().getColumn(0).setPreferredWidth(125);
            coursesTable.getColumnModel().getColumn(0).setMaxWidth(125);
            coursesTable.getColumnModel().getColumn(2).setMinWidth(90);
            coursesTable.getColumnModel().getColumn(2).setPreferredWidth(90);
            coursesTable.getColumnModel().getColumn(2).setMaxWidth(90);
            coursesTable.getColumnModel().getColumn(3).setMinWidth(95);
            coursesTable.getColumnModel().getColumn(3).setPreferredWidth(95);
            coursesTable.getColumnModel().getColumn(3).setMaxWidth(95);
            coursesTable.getColumnModel().getColumn(4).setMinWidth(100);
            coursesTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            coursesTable.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        registeredCoursesHeading.setBackground(new java.awt.Color(0, 102, 102));
        registeredCoursesHeading.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        registeredCoursesHeading.setForeground(new java.awt.Color(255, 255, 255));
        registeredCoursesHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registeredCoursesHeading.setText("Registered Courses");
        registeredCoursesHeading.setOpaque(true);

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-24.png"))); // NOI18N
        backButton.setOpaque(true);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        registerCourseButton.setBackground(new java.awt.Color(0, 102, 102));
        registerCourseButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        registerCourseButton.setForeground(new java.awt.Color(255, 255, 255));
        registerCourseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerCourseButton.setText("Register Course");
        registerCourseButton.setOpaque(true);
        registerCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerCourseButtonMouseClicked(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 102, 102));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-refresh-24.png"))); // NOI18N
        refreshButton.setOpaque(true);
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });

        deleteCourseButton.setBackground(new java.awt.Color(0, 102, 102));
        deleteCourseButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        deleteCourseButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteCourseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteCourseButton.setText("Delete Course");
        deleteCourseButton.setOpaque(true);
        deleteCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCourseButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(backButton)
                        .addGap(27, 27, 27)
                        .addComponent(refreshButton)
                        .addGap(328, 328, 328)
                        .addComponent(registeredCoursesHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(373, 373, 373)
                                .addComponent(registerCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(registeredCoursesHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        DashboardView dash = new DashboardView();
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void registerCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerCourseButtonMouseClicked
        CourseRegView courseRegView = new CourseRegView();
        courseRegView.show();
    }//GEN-LAST:event_registerCourseButtonMouseClicked

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        updateCourses();
    }//GEN-LAST:event_refreshButtonMouseClicked

    private void deleteCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCourseButtonMouseClicked
        DeleteCourse deleteCourse = new DeleteCourse();
        deleteCourse.setVisible(true);
    }//GEN-LAST:event_deleteCourseButtonMouseClicked
    
    public void updateCourses() {
    String username = CurrentUser.getUsername();
    Connection connection = null;
    try {
        connection = DatabaseConnection.getConnection();
        String query = "SELECT * FROM \"Course\" WHERE username = ?";
        
        try (PreparedStatement pstmt = connection.prepareStatement(query)) {
            pstmt.setString(1, username);
            
            try (ResultSet rs = pstmt.executeQuery()) {
                DefaultTableModel tableModel = (DefaultTableModel) coursesTable.getModel();
                
                // Clear existing rows
                tableModel.setRowCount(0);
                
                int rowCount = 0; // To track the number of rows processed
                
                while (rs.next()) {
                    String courseCode = rs.getString("coursecode");
                    String courseName = rs.getString("coursename");
                    int creditHours = rs.getInt("credithours");
                    String difficulty = rs.getString("difficulty");
                    double gpa = rs.getDouble("gpa");
                    
                    // Logging for debugging
                    
                    
                    // Convert numeric values to strings for the table
                    String creditHoursStr = String.valueOf(creditHours);
                    String gpaStr = String.valueOf(gpa);
                    
                    String[] tbData = {courseCode, courseName, creditHoursStr, difficulty, gpaStr};
                    tableModel.addRow(tbData);
                    
                    rowCount++; // Increment the row count
                }
                
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(CoursesView.class.getName()).log(Level.SEVERE, "Error updating courses", ex);
    }
      
}



    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel deleteCourseButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel refreshButton;
    private javax.swing.JLabel registerCourseButton;
    private javax.swing.JLabel registeredCoursesHeading;
    // End of variables declaration//GEN-END:variables
}
