/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Models.CurrentUser;

/**
 *
 * @author fahadxhussain
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardView() {
        initComponents();
        userName.setText(CurrentUser.getUsername());
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        changePassword = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        menuButton = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        changeName = new javax.swing.JLabel();
        CoursesButton = new javax.swing.JLabel();
        gradesButton = new javax.swing.JLabel();
        goalsButton = new javax.swing.JLabel();
        loginHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setSize(new java.awt.Dimension(1200, 800));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel2.setSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 150));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 150));
        jPanel1.setSize(new java.awt.Dimension(1200, 150));

        userName.setBackground(new java.awt.Color(0, 102, 102));
        userName.setFont(new java.awt.Font("Kefa", 1, 36)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("UserName");
        userName.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        userName.setOpaque(true);
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1200, 650));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 650));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 650));
        jPanel3.setSize(new java.awt.Dimension(1200, 650));

        sidebar.setBackground(new java.awt.Color(204, 204, 204));
        sidebar.setOpaque(false);
        sidebar.setPreferredSize(new java.awt.Dimension(100, 700));
        sidebar.setSize(new java.awt.Dimension(100, 700));

        changePassword.setBackground(new java.awt.Color(0, 102, 102));
        changePassword.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        changePassword.setForeground(new java.awt.Color(255, 255, 255));
        changePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePassword.setText("Change Password");
        changePassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordMouseClicked(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-24.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        menuButton.setBackground(new java.awt.Color(0, 102, 102));
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-vertical-24.png"))); // NOI18N
        menuButton.setOpaque(true);
        menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonMouseClicked(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 102, 102));
        logout.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Log Out");
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        changeName.setBackground(new java.awt.Color(0, 102, 102));
        changeName.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        changeName.setForeground(new java.awt.Color(255, 255, 255));
        changeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeName.setText("Change Name");
        changeName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(menuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(backButton))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(changePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97)
                .addComponent(changeName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        CoursesButton.setBackground(new java.awt.Color(0, 102, 102));
        CoursesButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        CoursesButton.setForeground(new java.awt.Color(255, 255, 255));
        CoursesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CoursesButton.setText("Courses");
        CoursesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CoursesButton.setOpaque(true);
        CoursesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoursesButtonMouseClicked(evt);
            }
        });

        gradesButton.setBackground(new java.awt.Color(0, 102, 102));
        gradesButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        gradesButton.setForeground(new java.awt.Color(255, 255, 255));
        gradesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradesButton.setText("Grades");
        gradesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gradesButton.setOpaque(true);
        gradesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradesButtonMouseClicked(evt);
            }
        });

        goalsButton.setBackground(new java.awt.Color(0, 102, 102));
        goalsButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        goalsButton.setForeground(new java.awt.Color(255, 255, 255));
        goalsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goalsButton.setText("Goals");
        goalsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goalsButton.setOpaque(true);
        goalsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goalsButtonMouseClicked(evt);
            }
        });

        loginHeader.setFont(new java.awt.Font("Kefa", 1, 36)); // NOI18N
        loginHeader.setForeground(new java.awt.Color(0, 102, 102));
        loginHeader.setText("Welcome To EduMetrica");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(CoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(gradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 335, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(loginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(349, 349, 349)
                                .addComponent(goalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(loginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addComponent(goalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        sidebar.setOpaque(false);
        sidebar.repaint();
        
        changeName.setOpaque(false);
        changeName.repaint();

        changePassword.setOpaque(false);
        changePassword.repaint();

        backButton.setOpaque(false);
        backButton.repaint();

        menuButton.setOpaque(true);
        menuButton.repaint();
        
        logout.setOpaque(false);
        logout.repaint();
    }//GEN-LAST:event_backButtonMouseClicked

    private void menuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonMouseClicked
        sidebar.setOpaque(true);
        sidebar.repaint();
        
        changeName.setOpaque(true);
        changeName.repaint();
        
        changePassword.setOpaque(true);
        changePassword.repaint();

        logout.setOpaque(true);
        logout.repaint();

        backButton.setOpaque(true);
        backButton.repaint();

        menuButton.setOpaque(false);
        menuButton.repaint();
    }//GEN-LAST:event_menuButtonMouseClicked

    private void CoursesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoursesButtonMouseClicked
        CoursesView courses = new CoursesView();
        courses.setVisible(true);
        courses.updateCourses();
        this.dispose();
    }//GEN-LAST:event_CoursesButtonMouseClicked

    private void gradesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesButtonMouseClicked
        GradesView gradesView = new GradesView();
        gradesView.show();
        
    }//GEN-LAST:event_gradesButtonMouseClicked

    private void goalsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goalsButtonMouseClicked
        GoalView goalView = new GoalView();
        goalView.setVisible(true);
        
    }//GEN-LAST:event_goalsButtonMouseClicked

    private void userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameMouseClicked

    private void changePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseClicked
        ChangePasswordView newPassword = new ChangePasswordView();
        newPassword.setVisible(true);
    }//GEN-LAST:event_changePasswordMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void changeNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeNameMouseClicked
        ChangeNameView newName = new ChangeNameView();
        newName.setVisible(true);
    }//GEN-LAST:event_changeNameMouseClicked
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoursesButton;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel changeName;
    private javax.swing.JLabel changePassword;
    private javax.swing.JLabel goalsButton;
    private javax.swing.JLabel gradesButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loginHeader;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menuButton;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
