/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Database.DatabaseConnection;
import Models.CurrentUser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fahadxhussain
 */
public class GoalView extends javax.swing.JFrame {

    /**
     * Creates new form GoalView
     */
    public GoalView() {
        initComponents();
        this.updateGoals();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        goalsTable = new javax.swing.JTable();
        addGoalButton = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        refreshButton = new javax.swing.JLabel();
        DeleteGoalbtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setSize(new java.awt.Dimension(1200, 800));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 100));
        jPanel2.setSize(new java.awt.Dimension(1200, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        goalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Goal", "Deadline", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        goalsTable.setRowHeight(32);
        jScrollPane1.setViewportView(goalsTable);

        addGoalButton.setBackground(new java.awt.Color(0, 102, 102));
        addGoalButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        addGoalButton.setForeground(new java.awt.Color(255, 255, 255));
        addGoalButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addGoalButton.setText("Add Goal");
        addGoalButton.setOpaque(true);
        addGoalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addGoalButtonMouseClicked(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-24.png"))); // NOI18N
        backButton.setOpaque(true);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 102, 102));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-refresh-24.png"))); // NOI18N
        refreshButton.setOpaque(true);
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });

        DeleteGoalbtn.setBackground(new java.awt.Color(0, 102, 102));
        DeleteGoalbtn.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        DeleteGoalbtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteGoalbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeleteGoalbtn.setText("Delete Goal");
        DeleteGoalbtn.setOpaque(true);
        DeleteGoalbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteGoalbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backButton)
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DeleteGoalbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(449, 449, 449)
                                .addComponent(addGoalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGoalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteGoalbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addGoalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGoalButtonMouseClicked
        AddGoalView addGoalView = new AddGoalView();
        addGoalView.setVisible(true);
        
        
    }//GEN-LAST:event_addGoalButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked

        DashboardView dashboard = new DashboardView();
        dashboard.show();
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        updateGoals();
    }//GEN-LAST:event_refreshButtonMouseClicked

    private void DeleteGoalbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteGoalbtnMouseClicked
        DeleteGoal deleteGoal = new DeleteGoal();
        deleteGoal.setVisible(true);
        
    }//GEN-LAST:event_DeleteGoalbtnMouseClicked

    public void updateGoals()
    {
        String username = CurrentUser.getUsername();
        Connection connection = null;
    try {
        connection = DatabaseConnection.getConnection();
        String query = "SELECT * FROM \"Goal\" WHERE username = ?";
        
        try (PreparedStatement pstmt = connection.prepareStatement(query)) {
            pstmt.setString(1, username);
            
            try (ResultSet rs = pstmt.executeQuery()) {
                DefaultTableModel tableModel = (DefaultTableModel) goalsTable.getModel();
                
                // Clear existing rows
                tableModel.setRowCount(0);
                
                int rowCount = 0; // To track the number of rows processed
                
                while (rs.next()) {
                    String goalInput = rs.getString("goal");
                    String deadLine = rs.getString("deadline");
                    
                    
                    
                    
                    String[] tbData = {goalInput, deadLine};
                    tableModel.addRow(tbData);
                    
                    rowCount++; // Increment the row count
                }
                
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(GoalView.class.getName()).log(Level.SEVERE, "Error updating courses", ex);
    }
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeleteGoalbtn;
    private javax.swing.JLabel addGoalButton;
    private javax.swing.JLabel backButton;
    private javax.swing.JTable goalsTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel refreshButton;
    // End of variables declaration//GEN-END:variables
}
