/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Database.DatabaseConnection;
import Models.CurrentUser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fahadxhussain
 */
public class GradesView extends javax.swing.JFrame {

    /**
     * Creates new form gradesView
     */
    public GradesView() {
        initComponents();
        updateGrades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradesTable = new javax.swing.JTable();
        overallGradesHeader = new javax.swing.JLabel();
        addGradesButton = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        DeleteGradebtn = new javax.swing.JLabel();
        refreshButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setSize(new java.awt.Dimension(1200, 800));

        gradesTable.setFont(new java.awt.Font("Al Nile", 1, 14)); // NOI18N
        gradesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Semester", "GPA", "Grades"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradesTable.setMaximumSize(new java.awt.Dimension(550, 600));
        gradesTable.setMinimumSize(new java.awt.Dimension(550, 600));
        gradesTable.setPreferredSize(new java.awt.Dimension(550, 600));
        gradesTable.setRowHeight(36);
        gradesTable.setShowGrid(false);
        gradesTable.setSize(new java.awt.Dimension(550, 600));
        jScrollPane1.setViewportView(gradesTable);

        overallGradesHeader.setBackground(new java.awt.Color(0, 102, 102));
        overallGradesHeader.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        overallGradesHeader.setForeground(new java.awt.Color(255, 255, 255));
        overallGradesHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overallGradesHeader.setText("Overall Grades");
        overallGradesHeader.setOpaque(true);

        addGradesButton.setBackground(new java.awt.Color(0, 102, 102));
        addGradesButton.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        addGradesButton.setForeground(new java.awt.Color(255, 255, 255));
        addGradesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addGradesButton.setText("Add Grades");
        addGradesButton.setOpaque(true);
        addGradesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addGradesButtonMouseClicked(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-24.png"))); // NOI18N
        backButton.setOpaque(true);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        DeleteGradebtn.setBackground(new java.awt.Color(0, 102, 102));
        DeleteGradebtn.setFont(new java.awt.Font("Kefa", 1, 18)); // NOI18N
        DeleteGradebtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteGradebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeleteGradebtn.setText("Delete Grades");
        DeleteGradebtn.setOpaque(true);
        DeleteGradebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteGradebtnMouseClicked(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 102, 102));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-refresh-24.png"))); // NOI18N
        refreshButton.setOpaque(true);
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(backButton)
                        .addGap(29, 29, 29)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(overallGradesHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DeleteGradebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overallGradesHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteGradebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addGradesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGradesButtonMouseClicked
        AddGradesView addGradesView = new AddGradesView();
        addGradesView.show();
    }//GEN-LAST:event_addGradesButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked

        DashboardView dashboard = new DashboardView();
        dashboard.show();
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void DeleteGradebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteGradebtnMouseClicked
        DeleteGrade deleteGrade = new DeleteGrade();
        deleteGrade.setVisible(true);
        
    }//GEN-LAST:event_DeleteGradebtnMouseClicked

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        updateGrades();
    }//GEN-LAST:event_refreshButtonMouseClicked

    
    public void updateGrades() {
    String username = CurrentUser.getUsername();
    Connection connection = null;
    try {
        connection = DatabaseConnection.getConnection();
        String query = "SELECT * FROM \"Grade\" WHERE username = ?";
        
        try (PreparedStatement pstmt = connection.prepareStatement(query)) {
            pstmt.setString(1, username);
            
            try (ResultSet rs = pstmt.executeQuery()) {
                DefaultTableModel tableModel = (DefaultTableModel) gradesTable.getModel();
                
                // Clear existing rows
                tableModel.setRowCount(0);
                
                int rowCount = 0; // To track the number of rows processed
                
                while (rs.next()) {
                    int semester = rs.getInt("semester");
                    double gpa = rs.getDouble("gpa");
                    String grades = rs.getString("grade");
                    
                    
                    // Logging for debugging
                    
                    
                    // Convert numeric values to strings for the table
                    String semesterStr = String.valueOf(semester);
                    String gpaStr = String.valueOf(gpa);
                    
                    String[] tbData = {semesterStr, gpaStr, grades};
                    tableModel.addRow(tbData);
                    
                    rowCount++; // Increment the row count
                }
                
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(CoursesView.class.getName()).log(Level.SEVERE, "Error updating courses", ex);
    }
      
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeleteGradebtn;
    private javax.swing.JLabel addGradesButton;
    private javax.swing.JLabel backButton;
    private javax.swing.JTable gradesTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel overallGradesHeader;
    private javax.swing.JLabel refreshButton;
    // End of variables declaration//GEN-END:variables
}
