/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Database.DatabaseConnection;
import Models.CurrentUser;
import Models.User;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author fahadxhussain
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    User user;
    private Connection connection;
    public LoginView() {
        initComponents();
        user = new User();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftSide = new javax.swing.JPanel();
        RightSide = new javax.swing.JPanel();
        mainLogo = new javax.swing.JLabel();
        loginHeader = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        signupText = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        LeftSide.setBackground(new java.awt.Color(255, 255, 255));
        LeftSide.setMaximumSize(new java.awt.Dimension(1200, 800));
        LeftSide.setMinimumSize(new java.awt.Dimension(1200, 800));
        LeftSide.setName("Login"); // NOI18N
        LeftSide.setPreferredSize(new java.awt.Dimension(1200, 800));
        LeftSide.setLayout(null);

        RightSide.setBackground(new java.awt.Color(0, 102, 102));
        RightSide.setMinimumSize(new java.awt.Dimension(600, 800));
        RightSide.setPreferredSize(new java.awt.Dimension(600, 400));

        mainLogo.setFont(new java.awt.Font("Kefa", 1, 48)); // NOI18N
        mainLogo.setForeground(new java.awt.Color(255, 255, 255));
        mainLogo.setText("EduMetrica");

        javax.swing.GroupLayout RightSideLayout = new javax.swing.GroupLayout(RightSide);
        RightSide.setLayout(RightSideLayout);
        RightSideLayout.setHorizontalGroup(
            RightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightSideLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(mainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        RightSideLayout.setVerticalGroup(
            RightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightSideLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(mainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(531, Short.MAX_VALUE))
        );

        LeftSide.add(RightSide);
        RightSide.setBounds(0, 0, 560, 800);

        loginHeader.setFont(new java.awt.Font("Kefa", 1, 36)); // NOI18N
        loginHeader.setForeground(new java.awt.Color(0, 102, 102));
        loginHeader.setText("Login");
        LeftSide.add(loginHeader);
        loginHeader.setBounds(850, 60, 100, 50);

        passwordLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 102, 102));
        passwordLabel.setText("Password");
        LeftSide.add(passwordLabel);
        passwordLabel.setBounds(770, 300, 110, 20);

        usernameLabel.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 102, 102));
        usernameLabel.setText("Username");
        LeftSide.add(usernameLabel);
        usernameLabel.setBounds(770, 210, 110, 20);

        PasswordField.setFont(new java.awt.Font("Al Nile", 0, 10)); // NOI18N
        PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        LeftSide.add(PasswordField);
        PasswordField.setBounds(770, 330, 260, 40);

        usernameField.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        LeftSide.add(usernameField);
        usernameField.setBounds(770, 230, 260, 40);

        signupText.setFont(new java.awt.Font("Al Nile", 0, 14)); // NOI18N
        signupText.setForeground(new java.awt.Color(0, 102, 102));
        signupText.setText("No Account? No Problem");
        LeftSide.add(signupText);
        signupText.setBounds(820, 580, 160, 30);

        loginButton.setBackground(new java.awt.Color(0, 102, 102));
        loginButton.setFont(new java.awt.Font("Kefa", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setDoubleBuffered(true);
        loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginButton.setMixingCutoutShape(null);
        loginButton.setOpaque(true);
        loginButton.setVerifyInputWhenFocusTarget(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        LeftSide.add(loginButton);
        loginButton.setBounds(850, 390, 100, 40);

        signupButton.setBackground(new java.awt.Color(0, 102, 102));
        signupButton.setFont(new java.awt.Font("Kefa", 1, 14)); // NOI18N
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("Sign Up");
        signupButton.setBorder(null);
        signupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupButton.setDoubleBuffered(true);
        signupButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signupButton.setMixingCutoutShape(null);
        signupButton.setOpaque(true);
        signupButton.setVerifyInputWhenFocusTarget(false);
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        LeftSide.add(signupButton);
        signupButton.setBounds(850, 620, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftSide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftSide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LeftSide.getAccessibleContext().setAccessibleName("Login");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = this.usernameField.getText();
        String password = this.PasswordField.getText();
        
        if(username.equals(""))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Please write your username", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Please enter your password", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
            boolean userAuthenticated = user.loginUser(username, password);
            if(userAuthenticated)
            {
                CurrentUser.setUsername(username);
                DashboardView dashboard = new DashboardView();
                dashboard.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(new JFrame(), "Incorrect username or password", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        

    }//GEN-LAST:event_loginButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        SignupView signupFrame = new SignupView();
        signupFrame.setVisible(true);
        signupFrame.pack();
        signupFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_signupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftSide;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel RightSide;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginHeader;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel signupText;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
